// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "yahu":return img`
...........fc...........
..........f22c..........
.........f2222c.........
.........f222b9c..ff....
........f2222b99cfff....
........f2222199cf2f....
........f222211b2f2f....
........f22221124ccf....
........f22229124ccf....
......fff22229b24cf.....
.....fc2f22222222cf.....
.....fcccc2222222f......
.....f22ff24c2222f......
.....fffff442c222f......
.....ffffc422c22c.......
.....ffff4422c22c.......
......ffc422cc2cc.......
........c222cc2c4c......
........c22ccc2244c.....
........c22cfc22244c....
.........cccf22f224c....
............f22cfffc....
............f2c.........
............ff..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
